### ISSUE TITLE
--port parameter gets ignored

### ISSUE THREAD

**Issue by FabiUnne** [hardoverflow/check-unifi#2]
Hey, 
Thank you for the check_script, found it on icinga-exchange.

There is a --port parameter, but it is not used anywhere in the script. 
Affects all lines where {args.host} occurs, lines 117, 159, 193-194.
Recommend writing `{args.host}:{args.port}`

**Comment by hardoverflow** [comment]
Thank you for your feedback! I add this in the next few days.
